### ISSUE TITLE
Write has no effect on the database

### ISSUE THREAD

**Issue by balugege** [lexmag/fluxter#15]
When I call `Bomb.Fluxter.write("credits", credits)` and then SHOW MEASUREMENTS in the influx cli i see nothing. No error is thrown.

Using fluxter 0.6.1.    

my config.exs     
```
config :fluxter,
  host: "localhost",
  port: 8086
```

my app entry point
```
defmodule Bomb do
  import Supervisor.Spec

  def start() do
    children = [
      Bomb.Fluxter.child_spec(),
    ]
    {:ok, pid} = Supervisor.start_link(children, strategy: :one_for_one)
  end
...
end
```

elixir --version
```
Erlang/OTP 20 [RELEASE CANDIDATE 2] [erts-9.0] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:10] [kernel-poll :false]

Elixir 1.4.4
```

**Comment by whatyouhide** [comment]
Hey @balugege, have you tried with Erlang 19 and Elixir 1.4.4 or Erlang 20 and Elixir 1.4.5? 1.4.4 doesn't support OTP 20. In any case, it would be really helpful if you could tell us more about your InfluxDB setup and would be great if you could provide a minimal example that reproduces this behaviour.

**Comment by lexmag** [comment]
Hey @balugege, do you have Telegraf in-between Fluxter and InfluxDB? Can you please check that your InfluxDB uses port 8086 and not the default one (8089)?

**Comment by balugege** [comment]
Hi, i am sorry but i never used that setup again so i can't give you any more details. Anyway thanks for your efforts

**Comment by lexmag** [comment]
No worries, I apologize that I'm late with my questions. :bowtie: 
I'm closing the issue then, but feel free to open if it happens again.
