### ISSUE TITLE
Dynamic host/port config

### ISSUE THREAD

**Issue by pikeas** [lexmag/fluxter#16]
Currently, `start_link/0` calls `Fluxster.config_for/1`. This seems to prevent runtime configuration of parameters.

Here are a few ways to improve this:

- Add `@defoverridable start_link: 0`
- Make `Fluxster.config_for` the default value for a new `config_fun` variable.
- Have `config_for` read from `System.get_env` before `Application.get_all_env`.
- Move `config_for` into `__using__` and make it overridable, and call it on the module rather than on Fluxter.

**Comment by rosacris** [comment]
I've submitted a pull request to implement such functionality.
https://github.com/lexmag/fluxter/pull/19
Enjoy!
