### ISSUE TITLE
Fluxter not pushing to telegraf

### ISSUE THREAD

**Issue by zmagajna** [lexmag/fluxter#18]
I have a problem with pushing to the Telegraf from a package. I have followed this article:[http://tech.footballaddicts.com/blog/gathering-metrics-in-elixir-applications](url)

I created a new model like was written in the article and added the module to my supervision tree.  In the configuration, I have added the configuration for local Telegraf service, but when I start the service nothing happens. There are no errors in the console of the app when starting the application. And when I check Telegraf logs, there is no send on the UDP port. 

Erlang version: Erlang/OTP 20
Elixir version: Elixir (1.5.1)
Fluxter version: 0.6.1
Telegraf version: 1.4.0-1

PS: The Application is an umbrella app, is that maybe the reason that Fluxter is not working?

**Comment by lexmag** [comment]
Just tried all these versions locally. Fluxter pushes metrics successfully. I believe umbrella app should not affect pushing, in fact, one of our application is umbrella—it works just fine.
@zmagajna can you please provide a sample project that reproduces the problem?

**Comment by zmagajna** [comment]
Hi @lexmag, at the end we choose elixometer and exometer, but when we were checking the logs with the Fluxer, there were no events coming in the client. We can close the issue.

**Comment by lexmag** [comment]
Thank you for letting me know. Closing the issue then.
