### ISSUE TITLE
Use poorboy instead of own worker pool implementation

### ISSUE THREAD

**Issue by hauleth** [lexmag/fluxter#25]
This should provide more flexible implementation.

**Comment by whatyouhide** [comment]
Do you mean "Poolboy"? If so, it wouldn't work too well with how Fluxter is designed (where you can just fire and forget on a connection). Checking out connections wouldn't bring benefits. Is there a particular reason you are proposing this? How would it be more flexible?

**Comment by lexmag** [comment]
Closing the issue for not having further feedback. @hauleth feel free to reopen. :bowtie:
