### ISSUE TITLE
UDP messages fail to send on OTP release 22

### ISSUE THREAD

**Issue by craigp** [lexmag/fluxter#29]
I had a crack at fixing this by switching out `send/2` with `:gen_udp.send/3` but I'm just not sure how the packet is constructed. Running the project tests will reproduce the error.

**Comment by rosacris** [comment]
I have sent a PR https://github.com/lexmag/fluxter/pull/28 a while ago to fix the issue but nobody merged it. That fix is working for us, we are using it in production.

**Comment by lexmag** [comment]
Fixed in 8981fd8b5579794f1575cc56a7167f39ff87f832.
