### ISSUE TITLE
Rename Fluxter.Batch

### ISSUE THREAD

**Issue by lexmag** [lexmag/fluxter#7]
I think it conveys incorrect meaning: collect several writes, not aggregate them into one.
@whatyouhide do you have any naming ideas? `Fluxter.Total` could work.

**Comment by whatyouhide** [comment]
I don't like `Fluxter.Total` personally as it doesn't say much on "total" of what, or how this "total" is calculated. Maybe something like `Fluxter.LocalCounter`? I'd like to try to convey the idea that 1. it's only for integers 2. it sums them and 3. it doesn't talk to InfluxDB until "flushed".

**Comment by whatyouhide** [comment]
Let's go with `Fluxter.Counter`.

**Comment by lexmag** [comment]
Closing in favor of the PR #10.
